
import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '../../providers';
import localfont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const hackNard = localfont({
  src: [
    {
      path: '/fonts/HackNerdFont-Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '/fonts/HackNerdFont-Bold.ttf',
      weight: '700',
      style: 'bold'
    },
    {
      path: '/fonts/HackNerdFont-Thin.ttf',
      weight: '100',
      style: 'thin'
    },

  ],
  display: 'swap',
});


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>): JSX.Element {
  return (
    <html lang='ja'>
      <body className={`${hackNard.className} text-sm text-black`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
